services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: mainspring_pocketbase
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./pocketbase/base/pb_data:/pb/pb_data
    # Run migrations before serving so all collections are created on first boot
    command: sh -c "/pb/pocketbase migrate up && /pb/pocketbase serve --http=0.0.0.0:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_POCKETBASE_URL: http://localhost:8080
        VITE_ASSET_URL: http://localhost:8080/api/files/watch_photos
    container_name: mainspring_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - pocketbase
