import { createFileRoute, Link } from '@tanstack/react-router';

export const Route = createFileRoute('/privacy-policy')({
  head: () => ({
    meta: [{ title: 'Privacy Policy — Hairspring' }],
  }),
  component: PrivacyPolicyPage,
});

function PrivacyPolicyPage() {
  return (
    <div className='min-h-screen bg-background font-sans text-foreground'>
      <div className='mx-auto max-w-180 px-6 pb-24 pt-12'>
        {/* Header */}
        <header className='mb-14 border-b border-border pb-5'>
          <Link
            to='/'
            className='font-serif text-xl font-bold tracking-wide text-ink no-underline'
          >
            Hairspring<span className='text-brass'>.</span>
          </Link>
        </header>

        {/* Title */}
        <h1 className='mb-2 font-serif text-3xl font-bold tracking-tight text-ink'>
          Privacy Policy
        </h1>
        <p className='mb-9 font-mono text-xs text-ink-faded'>
          Effective Date: May 10, 2026 · Last Updated: May 10, 2026
        </p>

        <p className='mb-4 text-ink-soft'>
          This Privacy Policy describes how Westmoreland Creative LLC ("we,"
          "us," or "our") collects, uses, and protects information you provide
          when using{' '}
          <strong className='font-semibold text-ink'>Hairspring</strong> ("the
          Service"), a watch repair tracking platform.
        </p>

        <hr className='my-9 border-border' />

        {/* Sections */}
        <Section number='1' title='Who We Are'>
          <P>
            Hairspring is operated by Westmoreland Creative LLC. If you have
            questions about this policy, contact us at{' '}
            <a href='mailto:support@westmorelandcreative.com'>
              support@westmorelandcreative.com
            </a>
            .
          </P>
        </Section>

        <Section number='2' title='Information We Collect'>
          <SubHeading>2.1 Account Information</SubHeading>
          <P>When you create an account, we collect:</P>
          <List
            items={[
              <>
                <Strong>Email address</Strong> — used for authentication and
                account communications
              </>,
              <>
                <Strong>Password</Strong> — stored as a one-way cryptographic
                hash; we never store your password in plaintext
              </>,
            ]}
          />

          <SubHeading>2.2 Profile Information</SubHeading>
          <P>You may optionally provide:</P>
          <List
            items={[
              'Display name (shown on your public profile if enabled)',
              'Biography',
              'Subdomain preference for your public profile page',
              'Public/private visibility setting for your profile',
            ]}
          />

          <SubHeading>2.3 Watch &amp; Repair Data</SubHeading>
          <P>
            The core purpose of the Service is to help you track watch repair
            projects. This includes data you enter about:
          </P>
          <List
            items={[
              <>
                <Strong>Watches:</Strong> make, model, reference number, year of
                manufacture, serial number, acquisition and sale dates, purchase
                and sale prices, repair status, condition, hours spent, notes,
                and listing URLs
              </>,
              <>
                <Strong>Photos:</Strong> images you upload of watches at various
                repair stages (before, during, after, listing), along with
                optional captions
              </>,
              <>
                <Strong>Repair posts:</Strong> titled journal entries with
                rich-text repair notes, session dates, and associated images
              </>,
              <>
                <Strong>Timegrapher readings:</Strong> rate, amplitude, and beat
                error measurements before and after service
              </>,
              <>
                <Strong>Parts &amp; inventory:</Strong> part names, categories,
                quantities, unit costs, supplier names, and notes
              </>,
              <>
                <Strong>Parts used:</Strong> records of which parts were applied
                to which watches, quantities, and dates
              </>,
              <>
                <Strong>Equipment:</Strong> tools and capital equipment with
                names, costs, acquisition dates, and supplier information
              </>,
            ]}
          />

          <SubHeading>2.4 Usage Data</SubHeading>
          <P>
            We collect standard server-side metadata generated by your use of
            the Service, including IP addresses, browser type, and request
            timestamps. This data is used solely for security monitoring and
            service operation.{' '}
            <Strong>
              We do not use any third-party analytics platforms or advertising
              networks.
            </Strong>
          </P>

          <SubHeading>2.5 Waitlist</SubHeading>
          <P>
            If you submitted your email to join the waitlist, we stored that
            email address for the sole purpose of notifying you when access was
            available.
          </P>
        </Section>

        <Section number='3' title='How We Use Your Information'>
          <List
            items={[
              'Provide, operate, and maintain the Service',
              'Authenticate your identity and secure your account',
              'Display your data back to you and compute financial summaries and statistics',
              'Respond to support requests and communications',
              'Detect and prevent unauthorized access or abuse',
              'Comply with legal obligations',
            ]}
          />
          <P>
            We do not sell, rent, or share your personal information with third
            parties for marketing purposes.
          </P>
        </Section>

        <Section number='4' title='Data Storage & Security'>
          <P>
            Your data is stored on servers operated by <Strong>Fly.io</Strong>{' '}
            in their <Strong>Chicago (ord)</Strong> region. Fly.io provides
            infrastructure-level security including encrypted storage and
            network isolation. Data is transmitted over TLS/HTTPS.
          </P>
          <P>
            Access to your data within the application is enforced through
            row-level security rules: you can only read or modify records that
            belong to your account.
          </P>
          <P>
            We implement reasonable technical and organizational measures to
            protect your data. No method of transmission or storage is 100%
            secure, and we cannot guarantee absolute security.
          </P>
        </Section>

        <Section number='5' title='Data Retention'>
          <P>
            We retain your data for as long as your account is active. If you
            delete your account, your personal data, watch records, photos,
            inventory, and all associated records are permanently deleted from
            our systems. Residual copies in backups are removed on a rolling
            basis within 30 days.
          </P>
        </Section>

        <Section number='6' title='Your Rights'>
          <List
            items={[
              <>
                <Strong>Access</Strong> — request a copy of the personal data we
                hold about you
              </>,
              <>
                <Strong>Correction</Strong> — update or correct inaccurate
                information via the Service
              </>,
              <>
                <Strong>Deletion</Strong> — request deletion of your account and
                all associated data
              </>,
              <>
                <Strong>Portability</Strong> — request an export of your data in
                a machine-readable format
              </>,
            ]}
          />
          <P>
            To exercise any of these rights, email us at{' '}
            <a href='mailto:support@westmorelandcreative.com'>
              support@westmorelandcreative.com
            </a>
            . We will respond within 30 days.
          </P>
          <P>
            If you are a resident of the European Economic Area (EEA) or United
            Kingdom, you may also have rights under GDPR or UK GDPR, including
            the right to lodge a complaint with your local supervisory
            authority.
          </P>
        </Section>

        <Section number='7' title='Cookies'>
          <P>
            The Service uses a session cookie to maintain your authenticated
            login state. We do not use tracking cookies, advertising cookies, or
            third-party cookies.
          </P>
        </Section>

        <Section number='8' title="Children's Privacy">
          <P>
            The Service is not directed to children under the age of 13. We do
            not knowingly collect personal information from children under 13.
            If you believe a child has provided us with personal information,
            contact us and we will delete it.
          </P>
        </Section>

        <Section number='9' title='Third-Party Services'>
          <P>
            The Service is built on infrastructure provided by{' '}
            <Strong>Fly.io</Strong> (hosting). Fly.io's own privacy practices
            apply to the infrastructure layer and are described at{' '}
            <a
              href='https://fly.io/legal/privacy-policy'
              target='_blank'
              rel='noopener noreferrer'
            >
              fly.io/legal/privacy-policy
            </a>
            .
          </P>
          <P>
            We do not integrate with third-party analytics, advertising
            networks, or social media platforms.
          </P>
        </Section>

        <Section number='10' title='Changes to This Policy'>
          <P>
            We may update this Privacy Policy from time to time. We will notify
            you of material changes by updating the "Last Updated" date at the
            top of this page and, where appropriate, by email. Continued use of
            the Service after changes take effect constitutes your acceptance of
            the updated policy.
          </P>
        </Section>

        <Section number='11' title='Contact'>
          <P>For privacy-related inquiries, contact:</P>
          <ContactCard />
        </Section>

        {/* Footer */}
        <footer className='mt-20 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-5'>
          <span className='font-mono text-[11px] text-ink-ghost'>
            © 2026 Westmoreland Creative LLC
          </span>
          <Link
            to='/terms-of-service'
            className='font-mono text-[11px] text-ink-faded no-underline hover:text-ink-soft'
          >
            Terms of Service →
          </Link>
        </footer>
      </div>
    </div>
  );
}

/* ── Shared primitives ─────────────────────────────────────────────────── */

function Section({
  number,
  title,
  children,
}: {
  number: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className='group mb-1 border-l-2 border-border pl-5 transition-colors hover:border-brass-light'>
      <h2 className='mb-3 mt-11 font-serif text-lg font-semibold tracking-wide text-ink'>
        {number}. {title}
      </h2>
      {children}
    </div>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return (
    <h3 className='mb-2 mt-6 font-mono text-[11px] font-medium uppercase tracking-widest text-brass'>
      {children}
    </h3>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p className='mb-3.5 text-[15px] text-ink-soft last:mb-0'>{children}</p>
  );
}

function Strong({ children }: { children: React.ReactNode }) {
  return <strong className='font-semibold text-ink'>{children}</strong>;
}

function List({ items }: { items: React.ReactNode[] }) {
  return (
    <ul className='mb-3.5 space-y-1.5'>
      {items.map((item, i) => (
        <li key={i} className='relative pl-5 text-[15px] text-ink-soft'>
          <span className='absolute left-0 text-ink-ghost'>—</span>
          {item}
        </li>
      ))}
    </ul>
  );
}

function ContactCard() {
  return (
    <div className='mt-3 rounded-md border border-border bg-paper-aged px-6 py-4'>
      <p className='font-serif text-[15px] font-semibold text-ink'>
        Westmoreland Creative LLC
      </p>
      <p className='mt-1 text-[15px] text-ink-soft'>
        Email:{' '}
        <a href='mailto:support@westmorelandcreative.com'>
          support@westmorelandcreative.com
        </a>
      </p>
    </div>
  );
}
