/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchesIndexRouteImport } from './routes/watches/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment/index'
import { Route as WatchesNewRouteImport } from './routes/watches/new'
import { Route as WatchWatchIdRouteImport } from './routes/watch/$watchId'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as PostPostIdRouteImport } from './routes/post/$postId'
import { Route as InventoryNewRouteImport } from './routes/inventory/new'
import { Route as EquipmentNewRouteImport } from './routes/equipment/new'
import { Route as WatchesWatchIdIndexRouteImport } from './routes/watches/$watchId/index'
import { Route as WatchesWatchIdTimegrapherRouteImport } from './routes/watches/$watchId/timegrapher'
import { Route as WatchesWatchIdShoppingListRouteImport } from './routes/watches/$watchId/shopping-list'
import { Route as WatchesWatchIdGalleryRouteImport } from './routes/watches/$watchId/gallery'
import { Route as WatchesWatchIdEditRouteImport } from './routes/watches/$watchId/edit'
import { Route as InventoryInventoryIdEditRouteImport } from './routes/inventory/$inventoryId/edit'
import { Route as EquipmentEquipmentIdEditRouteImport } from './routes/equipment/$equipmentId/edit'
import { Route as WatchesWatchIdPostsIndexRouteImport } from './routes/watches/$watchId/posts/index'
import { Route as WatchesWatchIdPostsNewRouteImport } from './routes/watches/$watchId/posts/new'
import { Route as WatchesWatchIdPostsPostIdRouteImport } from './routes/watches/$watchId/posts/$postId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesIndexRoute = WatchesIndexRouteImport.update({
  id: '/watches/',
  path: '/watches/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesNewRoute = WatchesNewRouteImport.update({
  id: '/watches/new',
  path: '/watches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchWatchIdRoute = WatchWatchIdRouteImport.update({
  id: '/watch/$watchId',
  path: '/watch/$watchId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentNewRoute = EquipmentNewRouteImport.update({
  id: '/equipment/new',
  path: '/equipment/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesWatchIdIndexRoute = WatchesWatchIdIndexRouteImport.update({
  id: '/watches/$watchId/',
  path: '/watches/$watchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesWatchIdTimegrapherRoute =
  WatchesWatchIdTimegrapherRouteImport.update({
    id: '/watches/$watchId/timegrapher',
    path: '/watches/$watchId/timegrapher',
    getParentRoute: () => rootRouteImport,
  } as any)
const WatchesWatchIdShoppingListRoute =
  WatchesWatchIdShoppingListRouteImport.update({
    id: '/watches/$watchId/shopping-list',
    path: '/watches/$watchId/shopping-list',
    getParentRoute: () => rootRouteImport,
  } as any)
const WatchesWatchIdGalleryRoute = WatchesWatchIdGalleryRouteImport.update({
  id: '/watches/$watchId/gallery',
  path: '/watches/$watchId/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesWatchIdEditRoute = WatchesWatchIdEditRouteImport.update({
  id: '/watches/$watchId/edit',
  path: '/watches/$watchId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryInventoryIdEditRoute =
  InventoryInventoryIdEditRouteImport.update({
    id: '/inventory/$inventoryId/edit',
    path: '/inventory/$inventoryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipmentEquipmentIdEditRoute =
  EquipmentEquipmentIdEditRouteImport.update({
    id: '/equipment/$equipmentId/edit',
    path: '/equipment/$equipmentId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const WatchesWatchIdPostsIndexRoute =
  WatchesWatchIdPostsIndexRouteImport.update({
    id: '/watches/$watchId/posts/',
    path: '/watches/$watchId/posts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WatchesWatchIdPostsNewRoute = WatchesWatchIdPostsNewRouteImport.update({
  id: '/watches/$watchId/posts/new',
  path: '/watches/$watchId/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesWatchIdPostsPostIdRoute =
  WatchesWatchIdPostsPostIdRouteImport.update({
    id: '/watches/$watchId/posts/$postId',
    path: '/watches/$watchId/posts/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pro': typeof ProRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wishlist': typeof WishlistRoute
  '/equipment/new': typeof EquipmentNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/post/$postId': typeof PostPostIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/watch/$watchId': typeof WatchWatchIdRoute
  '/watches/new': typeof WatchesNewRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/watches/': typeof WatchesIndexRoute
  '/equipment/$equipmentId/edit': typeof EquipmentEquipmentIdEditRoute
  '/inventory/$inventoryId/edit': typeof InventoryInventoryIdEditRoute
  '/watches/$watchId/edit': typeof WatchesWatchIdEditRoute
  '/watches/$watchId/gallery': typeof WatchesWatchIdGalleryRoute
  '/watches/$watchId/shopping-list': typeof WatchesWatchIdShoppingListRoute
  '/watches/$watchId/timegrapher': typeof WatchesWatchIdTimegrapherRoute
  '/watches/$watchId/': typeof WatchesWatchIdIndexRoute
  '/watches/$watchId/posts/$postId': typeof WatchesWatchIdPostsPostIdRoute
  '/watches/$watchId/posts/new': typeof WatchesWatchIdPostsNewRoute
  '/watches/$watchId/posts/': typeof WatchesWatchIdPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pro': typeof ProRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wishlist': typeof WishlistRoute
  '/equipment/new': typeof EquipmentNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/post/$postId': typeof PostPostIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/watch/$watchId': typeof WatchWatchIdRoute
  '/watches/new': typeof WatchesNewRoute
  '/equipment': typeof EquipmentIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/watches': typeof WatchesIndexRoute
  '/equipment/$equipmentId/edit': typeof EquipmentEquipmentIdEditRoute
  '/inventory/$inventoryId/edit': typeof InventoryInventoryIdEditRoute
  '/watches/$watchId/edit': typeof WatchesWatchIdEditRoute
  '/watches/$watchId/gallery': typeof WatchesWatchIdGalleryRoute
  '/watches/$watchId/shopping-list': typeof WatchesWatchIdShoppingListRoute
  '/watches/$watchId/timegrapher': typeof WatchesWatchIdTimegrapherRoute
  '/watches/$watchId': typeof WatchesWatchIdIndexRoute
  '/watches/$watchId/posts/$postId': typeof WatchesWatchIdPostsPostIdRoute
  '/watches/$watchId/posts/new': typeof WatchesWatchIdPostsNewRoute
  '/watches/$watchId/posts': typeof WatchesWatchIdPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pro': typeof ProRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wishlist': typeof WishlistRoute
  '/equipment/new': typeof EquipmentNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/post/$postId': typeof PostPostIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/watch/$watchId': typeof WatchWatchIdRoute
  '/watches/new': typeof WatchesNewRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/watches/': typeof WatchesIndexRoute
  '/equipment/$equipmentId/edit': typeof EquipmentEquipmentIdEditRoute
  '/inventory/$inventoryId/edit': typeof InventoryInventoryIdEditRoute
  '/watches/$watchId/edit': typeof WatchesWatchIdEditRoute
  '/watches/$watchId/gallery': typeof WatchesWatchIdGalleryRoute
  '/watches/$watchId/shopping-list': typeof WatchesWatchIdShoppingListRoute
  '/watches/$watchId/timegrapher': typeof WatchesWatchIdTimegrapherRoute
  '/watches/$watchId/': typeof WatchesWatchIdIndexRoute
  '/watches/$watchId/posts/$postId': typeof WatchesWatchIdPostsPostIdRoute
  '/watches/$watchId/posts/new': typeof WatchesWatchIdPostsNewRoute
  '/watches/$watchId/posts/': typeof WatchesWatchIdPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/privacy-policy'
    | '/pro'
    | '/signup'
    | '/terms-of-service'
    | '/wishlist'
    | '/equipment/new'
    | '/inventory/new'
    | '/post/$postId'
    | '/settings/profile'
    | '/watch/$watchId'
    | '/watches/new'
    | '/equipment/'
    | '/inventory/'
    | '/watches/'
    | '/equipment/$equipmentId/edit'
    | '/inventory/$inventoryId/edit'
    | '/watches/$watchId/edit'
    | '/watches/$watchId/gallery'
    | '/watches/$watchId/shopping-list'
    | '/watches/$watchId/timegrapher'
    | '/watches/$watchId/'
    | '/watches/$watchId/posts/$postId'
    | '/watches/$watchId/posts/new'
    | '/watches/$watchId/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/privacy-policy'
    | '/pro'
    | '/signup'
    | '/terms-of-service'
    | '/wishlist'
    | '/equipment/new'
    | '/inventory/new'
    | '/post/$postId'
    | '/settings/profile'
    | '/watch/$watchId'
    | '/watches/new'
    | '/equipment'
    | '/inventory'
    | '/watches'
    | '/equipment/$equipmentId/edit'
    | '/inventory/$inventoryId/edit'
    | '/watches/$watchId/edit'
    | '/watches/$watchId/gallery'
    | '/watches/$watchId/shopping-list'
    | '/watches/$watchId/timegrapher'
    | '/watches/$watchId'
    | '/watches/$watchId/posts/$postId'
    | '/watches/$watchId/posts/new'
    | '/watches/$watchId/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/privacy-policy'
    | '/pro'
    | '/signup'
    | '/terms-of-service'
    | '/wishlist'
    | '/equipment/new'
    | '/inventory/new'
    | '/post/$postId'
    | '/settings/profile'
    | '/watch/$watchId'
    | '/watches/new'
    | '/equipment/'
    | '/inventory/'
    | '/watches/'
    | '/equipment/$equipmentId/edit'
    | '/inventory/$inventoryId/edit'
    | '/watches/$watchId/edit'
    | '/watches/$watchId/gallery'
    | '/watches/$watchId/shopping-list'
    | '/watches/$watchId/timegrapher'
    | '/watches/$watchId/'
    | '/watches/$watchId/posts/$postId'
    | '/watches/$watchId/posts/new'
    | '/watches/$watchId/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProRoute: typeof ProRoute
  SignupRoute: typeof SignupRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WishlistRoute: typeof WishlistRoute
  EquipmentNewRoute: typeof EquipmentNewRoute
  InventoryNewRoute: typeof InventoryNewRoute
  PostPostIdRoute: typeof PostPostIdRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  WatchWatchIdRoute: typeof WatchWatchIdRoute
  WatchesNewRoute: typeof WatchesNewRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  WatchesIndexRoute: typeof WatchesIndexRoute
  EquipmentEquipmentIdEditRoute: typeof EquipmentEquipmentIdEditRoute
  InventoryInventoryIdEditRoute: typeof InventoryInventoryIdEditRoute
  WatchesWatchIdEditRoute: typeof WatchesWatchIdEditRoute
  WatchesWatchIdGalleryRoute: typeof WatchesWatchIdGalleryRoute
  WatchesWatchIdShoppingListRoute: typeof WatchesWatchIdShoppingListRoute
  WatchesWatchIdTimegrapherRoute: typeof WatchesWatchIdTimegrapherRoute
  WatchesWatchIdIndexRoute: typeof WatchesWatchIdIndexRoute
  WatchesWatchIdPostsPostIdRoute: typeof WatchesWatchIdPostsPostIdRoute
  WatchesWatchIdPostsNewRoute: typeof WatchesWatchIdPostsNewRoute
  WatchesWatchIdPostsIndexRoute: typeof WatchesWatchIdPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/': {
      id: '/watches/'
      path: '/watches'
      fullPath: '/watches/'
      preLoaderRoute: typeof WatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/new': {
      id: '/watches/new'
      path: '/watches/new'
      fullPath: '/watches/new'
      preLoaderRoute: typeof WatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$watchId': {
      id: '/watch/$watchId'
      path: '/watch/$watchId'
      fullPath: '/watch/$watchId'
      preLoaderRoute: typeof WatchWatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/new': {
      id: '/equipment/new'
      path: '/equipment/new'
      fullPath: '/equipment/new'
      preLoaderRoute: typeof EquipmentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId/': {
      id: '/watches/$watchId/'
      path: '/watches/$watchId'
      fullPath: '/watches/$watchId/'
      preLoaderRoute: typeof WatchesWatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId/timegrapher': {
      id: '/watches/$watchId/timegrapher'
      path: '/watches/$watchId/timegrapher'
      fullPath: '/watches/$watchId/timegrapher'
      preLoaderRoute: typeof WatchesWatchIdTimegrapherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId/shopping-list': {
      id: '/watches/$watchId/shopping-list'
      path: '/watches/$watchId/shopping-list'
      fullPath: '/watches/$watchId/shopping-list'
      preLoaderRoute: typeof WatchesWatchIdShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId/gallery': {
      id: '/watches/$watchId/gallery'
      path: '/watches/$watchId/gallery'
      fullPath: '/watches/$watchId/gallery'
      preLoaderRoute: typeof WatchesWatchIdGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId/edit': {
      id: '/watches/$watchId/edit'
      path: '/watches/$watchId/edit'
      fullPath: '/watches/$watchId/edit'
      preLoaderRoute: typeof WatchesWatchIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$inventoryId/edit': {
      id: '/inventory/$inventoryId/edit'
      path: '/inventory/$inventoryId/edit'
      fullPath: '/inventory/$inventoryId/edit'
      preLoaderRoute: typeof InventoryInventoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$equipmentId/edit': {
      id: '/equipment/$equipmentId/edit'
      path: '/equipment/$equipmentId/edit'
      fullPath: '/equipment/$equipmentId/edit'
      preLoaderRoute: typeof EquipmentEquipmentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId/posts/': {
      id: '/watches/$watchId/posts/'
      path: '/watches/$watchId/posts'
      fullPath: '/watches/$watchId/posts/'
      preLoaderRoute: typeof WatchesWatchIdPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId/posts/new': {
      id: '/watches/$watchId/posts/new'
      path: '/watches/$watchId/posts/new'
      fullPath: '/watches/$watchId/posts/new'
      preLoaderRoute: typeof WatchesWatchIdPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId/posts/$postId': {
      id: '/watches/$watchId/posts/$postId'
      path: '/watches/$watchId/posts/$postId'
      fullPath: '/watches/$watchId/posts/$postId'
      preLoaderRoute: typeof WatchesWatchIdPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProRoute: ProRoute,
  SignupRoute: SignupRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WishlistRoute: WishlistRoute,
  EquipmentNewRoute: EquipmentNewRoute,
  InventoryNewRoute: InventoryNewRoute,
  PostPostIdRoute: PostPostIdRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  WatchWatchIdRoute: WatchWatchIdRoute,
  WatchesNewRoute: WatchesNewRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  WatchesIndexRoute: WatchesIndexRoute,
  EquipmentEquipmentIdEditRoute: EquipmentEquipmentIdEditRoute,
  InventoryInventoryIdEditRoute: InventoryInventoryIdEditRoute,
  WatchesWatchIdEditRoute: WatchesWatchIdEditRoute,
  WatchesWatchIdGalleryRoute: WatchesWatchIdGalleryRoute,
  WatchesWatchIdShoppingListRoute: WatchesWatchIdShoppingListRoute,
  WatchesWatchIdTimegrapherRoute: WatchesWatchIdTimegrapherRoute,
  WatchesWatchIdIndexRoute: WatchesWatchIdIndexRoute,
  WatchesWatchIdPostsPostIdRoute: WatchesWatchIdPostsPostIdRoute,
  WatchesWatchIdPostsNewRoute: WatchesWatchIdPostsNewRoute,
  WatchesWatchIdPostsIndexRoute: WatchesWatchIdPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
