/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchesIndexRouteImport } from './routes/watches/index'
import { Route as WatchesNewRouteImport } from './routes/watches/new'
import { Route as WatchesWatchIdIndexRouteImport } from './routes/watches/$watchId/index'

const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesIndexRoute = WatchesIndexRouteImport.update({
  id: '/watches/',
  path: '/watches/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesNewRoute = WatchesNewRouteImport.update({
  id: '/watches/new',
  path: '/watches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesWatchIdIndexRoute = WatchesWatchIdIndexRouteImport.update({
  id: '/watches/$watchId/',
  path: '/watches/$watchId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/equipment': typeof EquipmentRoute
  '/inventory': typeof InventoryRoute
  '/watches/new': typeof WatchesNewRoute
  '/watches/': typeof WatchesIndexRoute
  '/watches/$watchId/': typeof WatchesWatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/equipment': typeof EquipmentRoute
  '/inventory': typeof InventoryRoute
  '/watches/new': typeof WatchesNewRoute
  '/watches': typeof WatchesIndexRoute
  '/watches/$watchId': typeof WatchesWatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/equipment': typeof EquipmentRoute
  '/inventory': typeof InventoryRoute
  '/watches/new': typeof WatchesNewRoute
  '/watches/': typeof WatchesIndexRoute
  '/watches/$watchId/': typeof WatchesWatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/equipment'
    | '/inventory'
    | '/watches/new'
    | '/watches/'
    | '/watches/$watchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/equipment'
    | '/inventory'
    | '/watches/new'
    | '/watches'
    | '/watches/$watchId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/equipment'
    | '/inventory'
    | '/watches/new'
    | '/watches/'
    | '/watches/$watchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EquipmentRoute: typeof EquipmentRoute
  InventoryRoute: typeof InventoryRoute
  WatchesNewRoute: typeof WatchesNewRoute
  WatchesIndexRoute: typeof WatchesIndexRoute
  WatchesWatchIdIndexRoute: typeof WatchesWatchIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/': {
      id: '/watches/'
      path: '/watches'
      fullPath: '/watches/'
      preLoaderRoute: typeof WatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/new': {
      id: '/watches/new'
      path: '/watches/new'
      fullPath: '/watches/new'
      preLoaderRoute: typeof WatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId/': {
      id: '/watches/$watchId/'
      path: '/watches/$watchId'
      fullPath: '/watches/$watchId/'
      preLoaderRoute: typeof WatchesWatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EquipmentRoute: EquipmentRoute,
  InventoryRoute: InventoryRoute,
  WatchesNewRoute: WatchesNewRoute,
  WatchesIndexRoute: WatchesIndexRoute,
  WatchesWatchIdIndexRoute: WatchesWatchIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
